# Generated by Django 5.2.7 on 2025-12-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_requisicao', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('APROVADA_PARCIAL', 'Aprovada Parcialmente'), ('NEGADA', 'Negada'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('observacao_solicitante', models.TextField(blank=True)),
                ('observacao_administrador', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('ROLO', 'Rolo')], max_length=10)),
                ('quantidade_estoque', models.IntegerField()),
                ('quantidade_minima', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.prefeitura')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.secretaria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.IntegerField()),
                ('quantidade_liberada', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.material')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
            },
        ),
    ]
