# Generated by Django 5.2.7 on 2025-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
