# Generated by Django 5.2.7 on 2025-12-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_setor'),
        ('estoque', '0003_material_categoria_material_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.setor'),
        ),
    ]
