# Generated by Django 5.2.7 on 2025-12-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_setor'),
        ('estoque', '0004_requisicao_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.material')),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.prefeitura')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.secretaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
            },
        ),
    ]
