# Generated by Django 5.2.7 on 2025-12-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_prefeitura_logo_secretaria_logo'),
        ('estoque', '0005_movimentoestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='orgao_externo',
            field=models.CharField(blank=True, choices=[('CONTROLADORIA_GERAL', 'Controladoria Geral do Município'), ('FMS_HOSPITAL_MUNICIPAL_JEH', 'FMS - HOSPITAL MUNICIPAL JOAO ELISIO DE HOLANDA'), ('FCDS', 'Fundação de Cultura e Desenvolvimento Social – FCDS'), ('FMAS', 'FUNDO MUNICIPAL DE ASSISTENCIA SOCIAL'), ('GABINETE_PREFEITO', 'Gabinete do Prefeito'), ('GABINETE_VICE_PREFEITO', 'Gabinete do Vice-Prefeito'), ('HOSPITAL_MUNICIPAL_JEH', 'Hospital Municipal João Elísio de Holanda'), ('OUVIDORIA_GERAL', 'Ouvidoria Geral do Município'), ('PROCURADORIA_GERAL', 'Procuradoria Geral do Município'), ('SEC_AGRICULTURA_FAMILIAR', 'Secretaria de Agricultura Familiar'), ('SEC_ASSISTENCIA_SOCIAL', 'Secretaria de Assistência Social e Segurança Alimentar'), ('SEC_CIENCIA_TECNOLOGIA', 'Secretaria de Ciência, Tecnologia, Inovação e Formação Tecnológica'), ('SEC_COMUNICACAO', 'Secretaria de Comunicação'), ('SEC_DESENVOLVIMENTO_ECONOMICO', 'Secretaria de Desenvolvimento Econômico'), ('SEC_EDUCACAO', 'Secretaria de Educação'), ('SEC_ESPORTE', 'Secretaria de Esporte'), ('SEC_GESTAO_ORCAMENTO_FINANCAS', 'Secretaria de Gestão, Orçamento e Finanças'), ('SEC_GOVERNO', 'Secretaria de Governo'), ('SEC_INCLUSAO_CIDADANIA', 'Secretaria de Inclusão e Cidadania'), ('SEC_INFRAESTRUTURA', 'Secretaria de Infraestrutura, Mobilidade e Controle Urbano'), ('SEC_JUVENTUDE_LAZER', 'Secretaria de Juventude e Lazer'), ('SEC_RECURSOS_HUMANOS', 'Secretaria de Recursos Humanos e Patrimoniais'), ('SEC_SAUDE', 'Secretaria de Saúde'), ('SEC_SEGURANCA_URBANA', 'Secretaria de Segurança Urbana'), ('SEC_BEM_ESTAR_ANIMAL', 'Secretaria do Bem-Estar Animal'), ('SEC_MEIO_AMBIENTE', 'Secretaria do Meio Ambiente'), ('SEC_TRABALHO_EMPREGO', 'Secretaria do Trabalho, Emprego e Empreendedorismo'), ('SEC_POVOS_ORIGINARIOS', 'Secretaria dos Povos Originários'), ('SEC_ESP_FAMILIA', 'Secretaria Especial da Família'), ('SEC_ESP_MULHER_DH', 'Secretaria Especial de Empoderamento da Mulher e dos Direitos Humanos'), ('SEC_ESP_INTEGRACAO_POLITICAS', 'Secretaria Especial de Integração de Políticas Sociais'), ('SEC_ESP_PARCEIRAS_CONCESSOES', 'Secretaria Especial de Parcerias e Concessões'), ('SEC_ESP_RELACOES_INSTITUCIONAIS', 'Secretaria Especial de Relações Institucionais')], max_length=80),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='tipo_negocio',
            field=models.CharField(choices=[('AJUSTE', 'Ajuste de estoque'), ('SUPRIMENTO_FUNDO', 'Suprimento de fundo'), ('EMPRESTIMO', 'Empréstimo'), ('DEVOLUCAO', 'Devolução')], default='AJUSTE', max_length=30),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NF', 'Nota Fiscal'), ('RECIBO', 'Recibo'), ('CI', 'Comunicação Interna'), ('OFICIO', 'Ofício'), ('OUTRO', 'Outro documento')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_estoque/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_estoque_criados', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.prefeitura')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.secretaria')),
            ],
            options={
                'verbose_name': 'Documento de Estoque',
                'verbose_name_plural': 'Documentos de Estoque',
            },
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='estoque.documentoestoque'),
        ),
    ]
