# Generated by Django 5.2.7 on 2025-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefeitura',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='prefeituras'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='secretarias'),
        ),
    ]
